serve:
  port: 8123
server:
  servlet:
    context-path: /api
spring:
  spplication:
    name: yu-picture-backend
    #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost；3306/yu-picture
    username: root
    password: 4321
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      login-delete-filed: isDelete #全局逻辑删除字段
      login-delete-value: 1 #逻辑已删除值
      login-not-delete-value: 0 #逻辑未删除值

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      test1:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.yupi.yupicturebackend.Controller